# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmt < Formula
  desc "Generate contextual git commit messages using Claude AI"
  homepage "https://github.com/gussy/cmt"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gussy/cmt/releases/download/v0.1.2/cmt_darwin_amd64.tar.gz"
      sha256 "79923b456024169eb989ca42139f89a09753e4930ba5b702b7bb2029f7c5a2c4"

      def install
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gussy/cmt/releases/download/v0.1.2/cmt_darwin_arm64.tar.gz"
      sha256 "8a417307f06fdc3cd9b3d0948dc59dc58bc3611b279b824e4a548716301df85b"

      def install
        bin.install "cmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gussy/cmt/releases/download/v0.1.2/cmt_linux_amd64.tar.gz"
      sha256 "bb91ad96484f27d7f4cc10bc1f5aeb8e117f6bb94ff850c16bca15185279b370"
      def install
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gussy/cmt/releases/download/v0.1.2/cmt_linux_arm64.tar.gz"
      sha256 "365be52b6ce792580a01de8c730dd8968517b29940aaa6aef93e4d138b033b2e"
      def install
        bin.install "cmt"
      end
    end
  end

  test do
    system "#{bin}/cmt --version"
  end
end
