# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmt" do
  name "cmt"
  desc "Generate contextual git commit messages using Claude AI"
  homepage "https://github.com/gussy/cmt"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmt"
  bash_completion "completions/cmt.bash"
  zsh_completion "completions/_cmt"
  fish_completion "completions/cmt.fish"

  on_macos do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_amd64.tar.gz"
      sha256 "dded63eff9d2452315db7615c70c236113d7e626219bdd561423ab6e2bbd7ffe"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_arm64.tar.gz"
      sha256 "a4c09afe726120853727691ecc6a4c540badf8ae90b6f68b94cb0875dea881ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_amd64.tar.gz"
      sha256 "c48787edd5b9daa71c835dd8247147ba0dcc9dd40fb1fdc406d503ac3094c12d"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_arm64.tar.gz"
      sha256 "2971077e5dc53728d55481c60d41c9de6e58bdd85e226a9d12acd38fe8f4ae3e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmt"]
    end
  end

  caveats do
    "Note: This tool removes macOS quarantine attributes to allow execution."
    "The binary is not code-signed or notarized by Apple."
  end

  # No zap stanza required
end
