# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmt" do
  name "cmt"
  desc "Generate contextual git commit messages using Claude AI"
  homepage "https://github.com/gussy/cmt"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmt"
  bash_completion "completions/cmt.bash"
  zsh_completion "completions/_cmt"
  fish_completion "completions/cmt.fish"

  on_macos do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_amd64.tar.gz"
      sha256 "28d4176dd23c6953ee2bde39b58e29d4148f7eaa06d64fe917cd837fb4fe87ce"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_arm64.tar.gz"
      sha256 "d59c0af20091e926c78b11a348d6fdb16605cbdaadc9614466253a27fdff037d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_amd64.tar.gz"
      sha256 "59541b4a916f832315dac9bf87a37117563930ab25a416d947ce01f094ea1c59"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_arm64.tar.gz"
      sha256 "450473c535a3568c52758591bc27b2ae2824db869a1d966b4269fdb3363891fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmt"]
    end
  end

  caveats do
    "Note: This tool removes macOS quarantine attributes to allow execution."
    "The binary is not code-signed or notarized by Apple."
  end

  # No zap stanza required
end
