# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmt" do
  name "cmt"
  desc "Generate contextual git commit messages using Claude AI"
  homepage "https://github.com/gussy/cmt"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmt"
  bash_completion "completions/cmt.bash"
  zsh_completion "completions/_cmt"
  fish_completion "completions/cmt.fish"

  on_macos do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_amd64.tar.gz"
      sha256 "2285a94a3bd6d0e32873c588a0b7a3535f6ee3040f95e759a67f3c9f6d9044fc"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_darwin_arm64.tar.gz"
      sha256 "3e0997cd4693efb9ad4fa04ef71276d04c3484dba132736e33fea9f2bc2c4e5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_amd64.tar.gz"
      sha256 "16586db63a9d1fe61e76d418c70e00e3e7fac016c6c68ed5df0181ae1d72ddee"
    end
    on_arm do
      url "https://github.com/Gussy/cmt/releases/download/v#{version}/cmt_linux_arm64.tar.gz"
      sha256 "8ab6e7879a22c9f0371e46c77f33cd9f7cdc085595623692ab341ee45c485399"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmt"]
    end
  end

  caveats do
    "Note: This tool removes macOS quarantine attributes to allow execution."
    "The binary is not code-signed or notarized by Apple."
  end

  # No zap stanza required
end
